# Generated by Django 4.1 on 2022-09-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('imageId', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('view', models.IntegerField(default=0)),
                ('click', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('grid', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
