# Generated by Django 4.1 on 2022-09-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.RemoveField(
            model_name='image',
            name='grid',
        ),
        migrations.RemoveField(
            model_name='image',
            name='weight',
        ),
        migrations.AddField(
            model_name='event',
            name='userId',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='image',
            name='categories',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='imageId',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
