# Generated by Django 4.1 on 2022-09-30 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category_remove_image_grid_remove_image_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='imageId',
            new_name='image_id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='userId',
            new_name='user_id',
        ),
    ]
