# Generated by Django 4.1 on 2022-09-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_imageid_event_image_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
