# Generated by Django 4.1.1 on 2022-10-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_event_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
