# Generated by Django 4.1.1 on 2022-10-04 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_category_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='number',
        ),
    ]
